on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - '**'
env:
  factorio_password: ${{ secrets.FACTORIO_PASSWORD }}
  factorio_username: ${{ secrets.FACTORIO_USERNAME }}
  FSM_MODPACK_DIR: 'dev_pack'
  FSM_DIR: '../'
  FSM_CONF: '../../conf.json.example'
jobs:
  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: make app/bundle
  test-go:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['1.20']
    runs-on: ${{ matrix.os }}
    name: test-go ${{ matrix.go }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: src/go.sum
      - if: contains(matrix.os, 'ubuntu')
        run: |
          cd src
          if [[ -z "$factorio_password" ]]; then
            echo "run only short tests"
            go test ./... -v -test.short
          else
            echo "run full test suit"
            go test ./... -v
          fi
      - if: contains(matrix.os, 'windows')
        run: |
          cd src
          if ([Environment]::GetEnvironmentVariable('factorio_password', 'Machine')) {
            echo "run full test suit"
            go test ./... -v
          } else {
            echo "run only short tests"
            go test ./... -v "-test.short"
          }
